export const FETCH_ALL_USER_REQ = "FETCH_ALL_USER_REQ";
export const FETCH_ALL_USER_SUCC = "FETCH_ALL_USER_SUCC";
export const FETCH_ALL_USER_FAIL = "FETCH_ALL_USER_FAIL";
export const FETCH_SINGLE_USER_REQ = "FETCH_SINGLE_USER_REQ";
export const FETCH_SINGLE_USER_SUCC = "FETCH_SINGLE_USER_SUCC";
export const FETCH_SINGLE_USER_FAIL = "FETCH_SINGLE_USER_FAIL";